/*
 * audio.h — RTP/SRTP fan-out plane for kerchunk-reflectd.
 *
 * Phase 3: reflector accepts SRTP-encrypted Opus packets on a UDP socket,
 * decrypts each with the sender's per-session key, then re-encrypts and
 * sends a copy to every other node on the sender's talkgroup. The reflector
 * never decodes Opus — it treats the cleartext payload as an opaque blob.
 *
 * Floor control on the audio path is intentionally absent in phase 3
 * (the plan says "without floor control" — phase 4 wires this in).
 */

#ifndef KERCHUNK_REFLECTD_AUDIO_H
#define KERCHUNK_REFLECTD_AUDIO_H

#include <stdint.h>
#include <netinet/in.h>

#include "../../vendor/mongoose.h"
#include "config.h"

/* Initialize libsrtp. Must be called once at startup before any audio
 * forwarding can happen. Returns 0 on success. */
int  audio_global_init(void);
void audio_global_shutdown(void);

/* Per-node audio session, populated at login. The master key + salt are
 * generated by the reflector and delivered in login_ok; both ends
 * derive their SRTP session keys from those via libsrtp's KDF. */
typedef struct audio_node_s audio_node_t;

audio_node_t *audio_node_create(const uint8_t *master_key,
                                const uint8_t *master_salt,
                                uint32_t       node_ssrc,
                                uint32_t       reflector_ssrc);
void          audio_node_destroy(audio_node_t *an);

/* Last-seen UDP source addr for this node (learned from the first RTP
 * packet that authenticates against this session). */
void audio_node_get_addr(const audio_node_t *an,
                         struct sockaddr_storage *out, socklen_t *out_len);
int  audio_node_have_addr(const audio_node_t *an);

/* Try to authenticate an inbound packet against this node's recv context.
 * Returns 0 if it auths and the (now decrypted) RTP packet is left in
 * pkt[0..*plen]; non-zero (libsrtp_err_status_t) on auth failure. */
int  audio_node_unprotect(audio_node_t *an,
                          uint8_t *pkt, int *plen,
                          const struct sockaddr_storage *src,
                          socklen_t src_len);

/* Encrypt + send a cleartext RTP packet (typically what came out of
 * audio_node_unprotect on another node) to this node, rewriting the
 * SSRC to reflector_ssrc and bumping the per-node outgoing sequence. */
int  audio_node_send_to(audio_node_t *an, int udp_fd,
                        const uint8_t *cleartext_rtp, int rtp_len);

#endif /* KERCHUNK_REFLECTD_AUDIO_H */
