/*
 * kerchunk_ini_edit.h — surgical INI section editing.
 *
 * Both kerchunkd's web-based config editor and kerchunk-reflectd's
 * roster editor need to add/replace/remove sections in an existing
 * INI file WITHOUT losing the operator's comments and hand-formatted
 * layout. The parser-based kerchunk_config_save() round-trips through
 * the in-memory key/value store and drops every comment, which is
 * fine for autogenerated configs but hostile for hand-edited ones.
 *
 * These helpers operate at the text level: read the file, find the
 * `[section]` header line, find the next section header (or EOF),
 * splice in the replacement, write atomically via tempfile + rename.
 *
 * Sections outside the touched one (and any leading-comment block
 * above the file's first section) are byte-for-byte preserved.
 */

#ifndef KERCHUNK_INI_EDIT_H
#define KERCHUNK_INI_EDIT_H

/* Replace (or insert if absent) the `[section]` block. `body` is the
 * section's contents WITHOUT the header line — caller writes the
 * header lines via the public API (e.g. "preshared_key_hex = ..."
 * one per line, ending in '\n'). Returns 0 on success, -1 on I/O
 * error. New sections are appended at EOF with a leading blank line. */
int kerchunk_ini_replace_section(const char *path, const char *section,
                                 const char *body);

/* Remove a `[section]` block and the immediately-following blank line
 * (so we don't leave double blanks). Idempotent — returns 0 even if
 * the section didn't exist. -1 on I/O error. */
int kerchunk_ini_remove_section(const char *path, const char *section);

#endif /* KERCHUNK_INI_EDIT_H */
