/*
 * gen_dcs_orbits.c — Generate DCS orbit (equivalence class) table.
 *
 * For each of the 104 DCS codes, compute all 23 cyclic rotations of
 * its codeword and its complement. Group codes whose codewords share
 * a rotation into the same orbit. Output a C table mapping each
 * raw 23-bit value to an orbit ID and preferred label.
 *
 * Build: cc -O2 -Ilibplcode/include -Ilibplcode/src -o gen_dcs_orbits \
 *        tools/gen_dcs_orbits.c libplcode/libplcode.a -lm
 * Run:   ./gen_dcs_orbits
 */

#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include "plcode_internal.h"

static int code_label(uint16_t c) {
    int r=0,m=1; while(c>0){r+=(c&7)*m;c>>=3;m*=10;} return r;
}

#define NC PLCODE_DCS_NUM_CODES

int main(void)
{
    plcode_tables_init();

    /* orbit_id[i] = orbit assignment for code index i */
    int orbit_id[NC];
    int orbit_inv[NC]; /* 1 if this code's canonical form is inverted */
    memset(orbit_id, -1, sizeof(orbit_id));
    memset(orbit_inv, 0, sizeof(orbit_inv));

    int num_orbits = 0;

    /* For each code, check if any rotation of its codeword (or complement)
     * matches any already-assigned code's codeword */
    for (int i = 0; i < NC; i++) {
        if (orbit_id[i] >= 0) continue; /* already assigned */

        uint32_t cw = plcode_dcs_codewords[i];
        int oid = num_orbits++;
        orbit_id[i] = oid;
        orbit_inv[i] = 0;

        /* Check all other codes against all 23 rotations + complement */
        for (int j = i + 1; j < NC; j++) {
            if (orbit_id[j] >= 0) continue;

            uint32_t cw_j = plcode_dcs_codewords[j];
            uint32_t comp_j = cw_j ^ 0x7FFFFF;

            /* Check all 23 rotations of code i's codeword */
            uint32_t rot = cw;
            for (int r = 0; r < 23; r++) {
                if (rot == cw_j) {
                    orbit_id[j] = oid;
                    orbit_inv[j] = 0;
                    break;
                }
                if (rot == comp_j) {
                    orbit_id[j] = oid;
                    orbit_inv[j] = 1;
                    break;
                }
                /* Rotate right by 1 */
                uint32_t lsb = rot & 1;
                rot = ((rot >> 1) | (lsb << 22)) & 0x7FFFFF;
            }

            /* Also check rotations of complement */
            if (orbit_id[j] < 0) {
                rot = cw ^ 0x7FFFFF;
                for (int r = 0; r < 23; r++) {
                    if (rot == cw_j) {
                        orbit_id[j] = oid;
                        orbit_inv[j] = 0;
                        break;
                    }
                    if (rot == comp_j) {
                        orbit_id[j] = oid;
                        orbit_inv[j] = 1;
                        break;
                    }
                    uint32_t lsb = rot & 1;
                    rot = ((rot >> 1) | (lsb << 22)) & 0x7FFFFF;
                }
            }
        }
    }

    printf("/* DCS Orbit Table — auto-generated by gen_dcs_orbits.c */\n\n");
    printf("/* %d codes map to %d distinct orbits */\n\n", NC, num_orbits);

    /* Print orbit assignments */
    printf("/* orbit_id, preferred_label, is_inverted_alias */\n");
    printf("static const struct {\n");
    printf("    uint8_t  orbit;     /* orbit ID */\n");
    printf("    uint16_t label;     /* DCS code label (e.g. 025) */\n");
    printf("    uint8_t  inv;       /* 1 = this label is an inverted alias */\n");
    printf("} dcs_orbit_table[%d] = {\n", NC);

    for (int i = 0; i < NC; i++) {
        int label = code_label(plcode_dcs_codes[i]);
        printf("    { %2d, %3d, %d }, /* DCS %03d */\n",
               orbit_id[i], label, orbit_inv[i], label);
    }
    printf("};\n\n");

    /* Print orbit summary */
    printf("/* Orbit summary: %d orbits */\n", num_orbits);
    for (int o = 0; o < num_orbits; o++) {
        printf("/* Orbit %2d: ", o);
        int first = 1;
        int preferred = -1;
        for (int i = 0; i < NC; i++) {
            if (orbit_id[i] != o) continue;
            int label = code_label(plcode_dcs_codes[i]);
            if (!first) printf(", ");
            printf("%03d%s", label, orbit_inv[i] ? "I" : "N");
            if (!orbit_inv[i] && preferred < 0) preferred = label;
            first = 0;
        }
        printf("  → preferred: %03d", preferred >= 0 ? preferred : code_label(plcode_dcs_codes[0]));
        printf(" */\n");
    }

    return 0;
}
