/*
 * gen_orbit_hash.c — Generate a perfect hash table mapping every
 * 23-bit shift register value (all rotations of all codewords)
 * to an orbit ID + preferred label.
 *
 * Output: C source for plcode_dcs_orbits.c
 *
 * Build: cc -O2 -Ilibplcode/include -Ilibplcode/src -o gen_orbit_hash \
 *        tools/gen_orbit_hash.c libplcode/libplcode.a -lm
 */

#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include <stdlib.h>
#include "plcode_internal.h"

static int code_label(uint16_t c) {
    int r=0,m=1; while(c>0){r+=(c&7)*m;c>>=3;m*=10;} return r;
}

#define NC PLCODE_DCS_NUM_CODES

/* Map entry: raw 23-bit value → orbit info */
typedef struct {
    uint32_t raw23;
    uint8_t  orbit_id;
    uint16_t preferred_label;
} orbit_entry_t;

#define MAX_ENTRIES (NC * 23 * 2 + 100)

static orbit_entry_t entries[MAX_ENTRIES];
static int num_entries;

static int find_entry(uint32_t raw) {
    for (int i = 0; i < num_entries; i++)
        if (entries[i].raw23 == raw) return i;
    return -1;
}

int main(void)
{
    plcode_tables_init();

    /* Compute orbits */
    int orbit_of[NC];
    int orbit_preferred[128]; /* preferred label per orbit */
    memset(orbit_of, -1, sizeof(orbit_of));
    int num_orbits = 0;

    for (int i = 0; i < NC; i++) {
        if (orbit_of[i] >= 0) continue;
        int oid = num_orbits++;
        orbit_of[i] = oid;
        orbit_preferred[oid] = code_label(plcode_dcs_codes[i]);

        uint32_t cw_i = plcode_dcs_codewords[i];
        for (int j = i + 1; j < NC; j++) {
            if (orbit_of[j] >= 0) continue;
            uint32_t cw_j = plcode_dcs_codewords[j];
            uint32_t comp_j = cw_j ^ 0x7FFFFF;
            uint32_t rot = cw_i;
            for (int r = 0; r < 23; r++) {
                if (rot == cw_j || rot == comp_j) { orbit_of[j] = oid; break; }
                uint32_t lsb = rot & 1;
                rot = ((rot >> 1) | (lsb << 22)) & 0x7FFFFF;
            }
            if (orbit_of[j] < 0) {
                rot = cw_i ^ 0x7FFFFF;
                for (int r = 0; r < 23; r++) {
                    if (rot == cw_j || rot == comp_j) { orbit_of[j] = oid; break; }
                    uint32_t lsb = rot & 1;
                    rot = ((rot >> 1) | (lsb << 22)) & 0x7FFFFF;
                }
            }
        }
    }

    /* Generate all rotations of all codewords (+ complements) */
    num_entries = 0;
    for (int i = 0; i < NC; i++) {
        uint32_t cw = plcode_dcs_codewords[i];
        int oid = orbit_of[i];
        int pref = orbit_preferred[oid];

        for (int pass = 0; pass < 2; pass++) {
            uint32_t w = (pass == 0) ? cw : (cw ^ 0x7FFFFF);
            uint32_t rot = w;
            for (int r = 0; r < 23; r++) {
                if (find_entry(rot) < 0 && num_entries < MAX_ENTRIES) {
                    entries[num_entries].raw23 = rot;
                    entries[num_entries].orbit_id = (uint8_t)oid;
                    entries[num_entries].preferred_label = (uint16_t)pref;
                    num_entries++;
                }
                uint32_t lsb = rot & 1;
                rot = ((rot >> 1) | (lsb << 22)) & 0x7FFFFF;
            }
        }
    }

    fprintf(stderr, "%d orbits, %d hash entries\n", num_orbits, num_entries);

    /* Output as C arrays */
    printf("/*\n");
    printf(" * DCS orbit lookup table — auto-generated by gen_orbit_hash.c\n");
    printf(" * Maps every possible 23-bit shift register value (all rotations\n");
    printf(" * of all 104 DCS codewords + complements) to an orbit ID and\n");
    printf(" * preferred display label.\n");
    printf(" *\n");
    printf(" * %d orbits, %d entries.\n", num_orbits, num_entries);
    printf(" */\n\n");

    printf("#define DCS_ORBIT_COUNT %d\n", num_orbits);
    printf("#define DCS_ORBIT_ENTRIES %d\n\n", num_entries);

    /* Use a simple hash table with open addressing */
    int hash_size = 8192; /* power of 2, ~1.7x entries */
    printf("#define DCS_ORBIT_HASH_SIZE %d\n", hash_size);
    printf("#define DCS_ORBIT_HASH_MASK %d\n\n", hash_size - 1);

    /* Build hash table */
    typedef struct { uint32_t key; uint8_t orbit; uint16_t label; } slot_t;
    slot_t *slots = calloc(hash_size, sizeof(slot_t));
    /* Mark empty with key = 0xFFFFFFFF */
    for (int i = 0; i < hash_size; i++) slots[i].key = 0xFFFFFFFF;

    int collisions = 0;
    for (int i = 0; i < num_entries; i++) {
        uint32_t h = (entries[i].raw23 * 2654435761u) >> 19; /* Knuth hash */
        h &= (hash_size - 1);
        while (slots[h].key != 0xFFFFFFFF) {
            h = (h + 1) & (hash_size - 1);
            collisions++;
        }
        slots[h].key = entries[i].raw23;
        slots[h].orbit = entries[i].orbit_id;
        slots[h].label = entries[i].preferred_label;
    }

    fprintf(stderr, "%d collisions in hash table (size %d)\n", collisions, hash_size);

    printf("static const struct {\n");
    printf("    uint32_t key;    /* 23-bit shift register value, 0xFFFFFFFF = empty */\n");
    printf("    uint16_t label;  /* preferred DCS code label */\n");
    printf("    uint8_t  orbit;  /* orbit ID */\n");
    printf("} dcs_orbit_hash[DCS_ORBIT_HASH_SIZE] = {\n");

    for (int i = 0; i < hash_size; i++) {
        if (slots[i].key == 0xFFFFFFFF) {
            printf("    {0xFFFFFFFF, 0, 0},\n");
        } else {
            printf("    {0x%06X, %3d, %2d},\n",
                   slots[i].key, slots[i].label, slots[i].orbit);
        }
    }
    printf("};\n\n");

    printf("/* Lookup: returns preferred label or 0 if not found */\n");
    printf("static inline uint16_t dcs_orbit_lookup(uint32_t sr23, uint8_t *orbit_out)\n");
    printf("{\n");
    printf("    uint32_t h = (sr23 * 2654435761u) >> 19;\n");
    printf("    h &= DCS_ORBIT_HASH_MASK;\n");
    printf("    for (int i = 0; i < 32; i++) { /* max probe */\n");
    printf("        if (dcs_orbit_hash[h].key == sr23) {\n");
    printf("            if (orbit_out) *orbit_out = dcs_orbit_hash[h].orbit;\n");
    printf("            return dcs_orbit_hash[h].label;\n");
    printf("        }\n");
    printf("        if (dcs_orbit_hash[h].key == 0xFFFFFFFF) return 0;\n");
    printf("        h = (h + 1) & DCS_ORBIT_HASH_MASK;\n");
    printf("    }\n");
    printf("    return 0;\n");
    printf("}\n");

    free(slots);
    return 0;
}
